import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { readFileSync, writeFileSync } from "node:fs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = join(root, ".env");
const outPath = join(root, "public", "firebase-messaging-sw.js");
const logicPath = join(root, "scripts", "push-sw-logic.js");

const FIREBASE_CDN = "12.15.0";

function loadDotEnv(filePath) {
  const env = { ...process.env };
  try {
    const text = readFileSync(filePath, "utf8");
    for (const line of text.split(/\r?\n/)) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eq = trimmed.indexOf("=");
      if (eq === -1) continue;
      const key = trimmed.slice(0, eq).trim();
      let value = trimmed.slice(eq + 1).trim();
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }
      env[key] = value;
    }
  } catch {
    // .env 없으면 process.env만 사용 (GHA build)
  }
  return env;
}

function requireEnv(env, key) {
  const value = env[key];
  if (!value) {
    console.warn(`[generate-fcm-sw] skip: missing ${key}`);
    return null;
  }
  return value;
}

const env = loadDotEnv(envPath);

const config = {
  apiKey: requireEnv(env, "VITE_FIREBASE_API_KEY"),
  authDomain: requireEnv(env, "VITE_FIREBASE_AUTH_DOMAIN"),
  projectId: requireEnv(env, "VITE_FIREBASE_PROJECT_ID"),
  messagingSenderId: requireEnv(env, "VITE_FIREBASE_MESSAGING_SENDER_ID"),
  appId: requireEnv(env, "VITE_FIREBASE_APP_ID"),
};

const sharedLogic = readFileSync(logicPath, "utf8");

if (!Object.values(config).every(Boolean)) {
  const stub = `// Firebase env 미설정 — .env 또는 GHA Secrets 확인 후 prebuild 실행
${sharedLogic}
self.addEventListener("notificationclick", handleNotificationClick);
`;
  writeFileSync(outPath, stub, "utf8");
  console.warn("[generate-fcm-sw] wrote stub (Firebase env incomplete)");
  process.exit(0);
}

const swSource = `/* generated by scripts/generate-fcm-sw.mjs — do not edit */
importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_CDN}/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_CDN}/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(config, null, 2)});

const messaging = firebase.messaging();

${sharedLogic}

messaging.onBackgroundMessage(function (payload) {
  var alert = buildAlertFromPayload(payload);
  var body = String(alert.body || "").replace(/\\\\n/g, "\\n");
  var notificationData = Object.assign({}, payload.data || {}, {
    fingerprint: alert.fingerprint,
    receivedAt: alert.receivedAt,
    title: alert.title,
    body: alert.body,
    url: alert.url,
    topic: alert.topic,
  });

  return saveAlertToIdb(alert)
    .catch(function () {
      return undefined;
    })
    .then(function () {
      return self.registration.showNotification(alert.title, {
        body: body,
        tag: alert.fingerprint,
        icon: "/icons/icon-192.png",
        badge: "/icons/icon-192.png",
        data: notificationData,
      });
    });
});

self.addEventListener("notificationclick", handleNotificationClick);
`;

writeFileSync(outPath, swSource, "utf8");
console.log(`[generate-fcm-sw] wrote ${outPath}`);
